'''
Created on 2-jan.-2017

@author: thomas
'''

WINDOWWIDTH = 800
WINDOWHEIGHT = 600
SCREENSIZE = (WINDOWWIDTH, WINDOWHEIGHT)

BOXSIZE = 60
BOARDSIZE = 8
BOARDWIDTH = BOARDHEIGHT = BOXSIZE * BOARDSIZE
BOARDMARGIN = 10
XMARGIN = (WINDOWWIDTH - BOARDWIDTH) // 2 - BOARDMARGIN
YMARGIN = (WINDOWHEIGHT - BOARDHEIGHT) // 2 - BOARDMARGIN

STONESIZE = BOXSIZE // 5 * 2

FPS = 30

BLACKVAL = -1
WHITEVAL = 1
EMPTY = 0

PLAYER = 'Player'
COMPUTER = 'Computer'

WHITE    = (255, 255, 255)
BLACK    = (  0,   0,   0)
RED      = (255,   0,   0)
BGCOLOUR = (  0, 124, 255)
BOARDCOLOUR = (64, 192, 255)

P = { BLACKVAL: PLAYER, 
      WHITEVAL: COMPUTER }
PCOLOUR = { BLACKVAL: BLACK, 
            WHITEVAL: WHITE }
